---
home_web_symlink_owner: debian

certbot_certificates:
  - name: leo.surf
    domains:
      - leo.surf
      - www.leo.surf
  - name: stats.leo.surf
    domains:
      - stats.leo.surf
  - name: estcequilfaitchaud.fr
    domains:
      - estcequilfaitchaud.fr
      - www.estcequilfaitchaud.fr

managed_nginx_conf_files:
  - default.conf
  - leo.surf.conf
  - stats.leo.surf.conf
  - estcequilfaitchaud.fr.conf

nginx_required_directories:
  - "{{ nginx_conf_dir }}"
  - "{{ nginx_html_root }}"
  - "{{ nginx_html_root }}/leo.surf"
  - "{{ nginx_html_root }}/estcequilfaitchaud.fr"
  - "{{ certbot_webroot }}"
  - "{{ letsencrypt_dir }}"
  - "{{ letsencrypt_dir }}/renewal-hooks/deploy"

nginx_sites:
  - name: leo.surf
    jinjapocalypse_git_source: https://github.com/mortrevere/leo.surf.git
    output: leo.surf.conf
    servers:
      - names:
          - leo.surf
          - www.leo.surf
        ssl:
          cert_name: leo.surf
          include_options: false
        locations:
          - path: /
            root: "{{ nginx_html_root }}/leo.surf/"
            cors_any_origin: true
      - names:
          - leo.surf
          - www.leo.surf
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

  - name: stats.leo.surf
    output: stats.leo.surf.conf
    servers:
      - names:
          - stats.leo.surf
        ssl:
          cert_name: stats.leo.surf
          include_options: false
        proxy_locations:
          - path: /
            upstream: http://localhost:3000/
      - names:
          - stats.leo.surf
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

  - name: estcequilfaitchaud.fr
    output: estcequilfaitchaud.fr.conf
    www_source: estcequilfaitchaud.fr/index.html
    www_dest: "{{ nginx_html_root }}/estcequilfaitchaud.fr/"
    servers:
      - names:
          - estcequilfaitchaud.fr
          - www.estcequilfaitchaud.fr
        ssl:
          cert_name: estcequilfaitchaud.fr
          include_options: false
        locations:
          - path: /
            root: "{{ nginx_html_root }}/estcequilfaitchaud.fr/"
      - names:
          - estcequilfaitchaud.fr
          - www.estcequilfaitchaud.fr
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"
