---
home_web_symlink_owner: debian

certbot_certificates:
  - name: leo.surf
    domains:
      - leo.surf
      - www.leo.surf

managed_nginx_conf_files:
  - default.conf
  - leo.surf.conf

nginx_required_directories:
  - "{{ nginx_conf_dir }}"
  - "{{ nginx_html_root }}"
  - "{{ nginx_html_root }}/leo.surf"
  - "{{ certbot_webroot }}"
  - "{{ letsencrypt_dir }}"
  - "{{ letsencrypt_dir }}/renewal-hooks/deploy"

nginx_sites:
  - name: leo.surf
    jinjapocalypse_git_source: https://github.com/mortrevere/leo.surf.git
    output: leo.surf.conf
    servers:
      - names:
          - leo.surf
          - www.leo.surf
        ssl:
          cert_name: leo.surf
          include_options: false
        locations:
          - path: /
            root: "{{ nginx_html_root }}/leo.surf/"
            cors_any_origin: true
        proxy_locations:
          - path: /umami
            exact: true
            redirect_to: /umami/
          - path: /umami/
            upstream: http://localhost:3000/
      - names:
          - leo.surf
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"
