---
home_web_symlink_owner: debian

firewall_allowed_udp_ports:
  - "{{ wireguard_listen_port }}"
firewall_extra_input_rules:
  - iif "wg0" tcp dport 9100 ip saddr 100.64.88.0/24 accept

wireguard_enabled: true

certbot_certificates:
  - name: leo.surf
    domains:
      - leo.surf
      - www.leo.surf
  - name: stats.leo.surf
    domains:
      - stats.leo.surf
  - name: estcequilfaitchaud.fr
    domains:
      - estcequilfaitchaud.fr
      - www.estcequilfaitchaud.fr
  - name: below.black
    domains:
      - below.black
      - www.below.black
  - name: below.industries
    domains:
      - below.industries
  - name: leshauts.xyz
    domains:
      - leshauts.xyz

nginx_required_directories:
  - "{{ nginx_conf_dir }}"
  - "{{ nginx_html_root }}"
  - "{{ nginx_html_root }}/leo.surf"
  - "{{ nginx_html_root }}/estcequilfaitchaud.fr"
  - "{{ nginx_html_root }}/below.industries"
  - "{{ nginx_html_root }}/below.black"
  - "{{ nginx_html_root }}/leshauts.xyz"
  - "{{ certbot_webroot }}"
  - "{{ letsencrypt_dir }}"
  - "{{ letsencrypt_dir }}/renewal-hooks/deploy"

nginx_sites:
  - name: leo.surf
    jinjapocalypse_git_source: https://github.com/mortrevere/leo.surf.git
    servers:
      - names:
          - leo.surf
          - www.leo.surf
        ssl:
          cert_name: leo.surf
        locations:
          - path: /
            root: "{{ nginx_html_root }}/leo.surf/"
            cors_any_origin: true
      - names:
          - leo.surf
          - www.leo.surf
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

  - name: stats.leo.surf
    servers:
      - names:
          - stats.leo.surf
        ssl:
          cert_name: stats.leo.surf
        proxy_locations:
          - path: /
            upstream: http://localhost:3000/
      - names:
          - stats.leo.surf
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

  - name: estcequilfaitchaud.fr
    www_source: estcequilfaitchaud.fr/index.html
    servers:
      - names:
          - estcequilfaitchaud.fr
          - www.estcequilfaitchaud.fr
        ssl:
          cert_name: estcequilfaitchaud.fr
        locations:
          - path: /
            root: "{{ nginx_html_root }}/estcequilfaitchaud.fr/"
            cors_any_origin: true
      - names:
          - estcequilfaitchaud.fr
          - www.estcequilfaitchaud.fr
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

  - name: below.industries
    jinjapocalypse_git_source: https://github.com/beLow-Industries/below.industries.git
    servers:
      - names:
          - below.industries
        ssl:
          cert_name: below.industries
        locations:
          - path: /
            root: "{{ nginx_html_root }}/below.industries/"
            cors_any_origin: true

      - names:
          - below.industries
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

  - name: leshauts.xyz
    www_source: leshauts.xyz/
    www_dest: "{{ nginx_html_root }}/leshauts.xyz/"
    www_deploy_strategy: rsync_checksum
    servers:
      - names:
          - leshauts.xyz
        ssl:
          cert_name: leshauts.xyz
        locations:
          - path: /hydrologie/
            root: "{{ nginx_html_root }}/leshauts.xyz"
          - path: /romejko/
            alias: "{{ nginx_html_root }}/leshauts.xyz/romejko/build/"
          - path: /
            root: "{{ nginx_html_root }}/leshauts.xyz"
        error_pages: true

      - names:
          - leshauts.xyz
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

  - name: below.black
    jinjapocalypse_git_source: https://github.com/mortrevere/below.black.git
    servers:
      - names:
          - below.black
        no_cache: true
        ssl:
          cert_name: below.black
        locations:
          - path: /
            root: "{{ nginx_html_root }}/below.black/"
            cors_any_origin: true

      - names:
          - www.below.black
        return_directive: "301 https://below.black$request_uri"
        ssl:
          cert_name: below.black

      - names:
          - below.black
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://$host$request_uri"

      - names:
          - www.below.black
        listen:
          - "80"
        acme_challenge: true
        redirect_to_https: "https://below.black$request_uri"
